version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: retail_postgres
    environment:
      POSTGRES_DB: retail_procurement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: src/RetailProcurement.API/Dockerfile
    container_name: retail_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=retail_procurement;Username=postgres;Password=postgres
      - JwtSettings__SecretKey=RetailProcurementSuperSecretKey2024!MustBe32CharsLong
      - JwtSettings__Issuer=RetailProcurementAPI
      - JwtSettings__Audience=RetailProcurementClient
      - JwtSettings__ExpiresInHours=24
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: frontend/retail-procurement-ui
      dockerfile: Dockerfile
    container_name: retail_frontend
    ports:
      - "4200:80"
    depends_on:
      - api

volumes:
  postgres_data:
